### ISSUE TITLE
Not shown GYM info after transform from pokestop

### ISSUE THREAD

**Issue by lukyrys** [cecpk/RocketMAD#111]
hi, i have problem with gym transformed from pokestops.. in rocketmap not shown info 

```
TypeError: e is undefined                                    map.common.built.js:622:4
    isValidRaid map.common.built.js:622
    isGymMeetsRaidFilters map.built.js:2626
    gymLabel map.built.js:1528
    showGymDetails map.built.js:3933
    jQuery 4

```

Response from ajax call
```
{
  "costume": null,
  "description": null,
  "form": null,
  "gender": null,
  "guard_pokemon_id": 306,
  "guard_pokemon_name": "Aggron",
  "gym_id": "79eda1e0de344883981af1a7c8e59d3d.16",
  "is_ex_raid_eligible": false,
  "is_in_battle": false,
  "last_modified": 1569539189000,
  "last_scanned": 1569539286000,
  "latitude": 50.050235,
  "longitude": 14.990434,
  "name": "Padlym Hrdinum 1914-1919",
  "shiny": null,
  "slots_available": 3,
  "team_id": 1,
  "total_cp": 0,
  "url": "http://lh6.ggpht.com/5PQBo4XgyjPm5Lwyb5wVXn4oCFAeRLHWdwxz7BtJxALdKIbVHPRj4ftaTt3Q2fa4sKdcg9gx1L4VdaM6xIRy",
  "weather_boosted_condition": null
}
```

## Steps to Reproduce (for bugs)
1) http://85.163.111.6:5555/
2) Gym at location 50.050235, 14.990434
3) Click on it 
4) In debug console is this http://502.cz/scr/firefox_2019-09-25_01-53-25.png
Other gyms are ok

## Your Environment

* Version used:  Latest (f37bc7c8) develop commit 
* Environment name and version: Python 3.6.3
* Operating System and version (desktop or mobile): virtual server with Debian GNU/Linux 9.9 (stretch)

**Comment by daangroot** [comment]
My assumption is that MAD didn't update the gym_id correctly. I think that gym is still using the pokestop_id and therefore can't retrieve the data from the Raid table. I noticed that the problem no longer occurs for this gym. Can you check if the gym_id for this gym has changed?

**Comment by lukyrys** [comment]
I tried to delete gym from the database but no result. Now the gym has the same gym_ id "79eda1e0de344883981af1a7c8e59d3d.16"
But amazing.. it fixed "itself" without further intervention
