### ISSUE TITLE
Feature Request: Ability to Mark Raids Complete (through removal)

### ISSUE THREAD

**Issue by dcooper0591** [cecpk/RocketMAD#161]
I would like to be able to remove a raid from my map after I complete the raid. This feature is available for pokemon currently and I would like it for raids as well.

## Expected Behavior

By clicking on a raid to see the raid details I can see a trash icon next to the hide icon. Clicking this would remove only this specific raid from my map.

## Current Behavior

Currently there is no availability for this. The current "hide" icon alters the filter to exclude that mon from the map, removing all raids of that pokemon from the map at once.

## Possible Solution

The pokemon details screen has this trash icon on it currently. It currently exhibits the expected behavior I mentioned above, and would be perfect for this use case. 

Solution: Add trash icon to raid details screen, this would remove this raid only from the map.

## Context

Use Case: 

I do speed raiding and like to plan the optimal route to do raids. Currently I just have to remember which raids I've done and plan my route accordingly. It would be much easier if after my group completes the raid, I can press the trash icon and the map would then hide the raid from my map, allowing me to see any new raids that pop up and any raids I haven't done yet so I can continue to plan my route with ease.

**Comment by HELLspawnTIM** [comment]
The same could be done for Pokestops with Quests

**Comment by dcooper0591** [comment]
Yes that would be great to have as well

**Comment by pki0** [comment]
You can try #196 .

**Comment by dcooper0591** [comment]
Awesome, thank you, I'll give it a try!
