### ISSUE TITLE
Security configuration nginx

### ISSUE THREAD

**Issue by korentzari** [cecpk/RocketMAD#163]
Configuration nginx send all files not on appserver.
Is very important problem for config/config.ini per exemple

## Possible Solution
location /config {
     deny all;
     return 418;
}

## Steps to Reproduce (for bugs)
curl https://domain.com/configs/config.ini

**Comment by sn0opy** [comment]
Did you misconfigure your Nginx? For a working RM, you usually just need this configuration:

```
server {
  listen 443 ssl http2;
  server_name map.domain.com;
  gzip on;
  gzip_types *;
  charset UTF-8;

  access_log off;

  ssl_certificate /etc/nginx/ssl/map.domain.com.pem;
  ssl_certificate_key /etc/nginx/ssl/map.domain.com.key;

  location / {
    proxy_pass http://127.0.0.1:31337;
  }
}
```

Every request will be proxied to the RM python server which does not return any of the configs content for me.

**Comment by na-ji** [comment]
If you're talking about the example in the [documentation](https://github.com/cecpk/RocketMAD/blob/master/docs/advanced-install/nginx.md), I see why it would happen. I think the best solution is to only expose the static folder, since that's what this config wanted to do.

**Comment by daangroot** [comment]
Fixed in https://github.com/cecpk/RocketMAD/commit/0e3190d1421ea8494ddeb050f0087db429943150
