### ISSUE TITLE
I don't see pokemon on the map

### ISSUE THREAD

**Issue by xenud** [cecpk/RocketMAD#165]
## Expected Behavior

I started the application without problems but I can't see anything on the map

## Current Behavior

I expected to be able to see pokemon and pokestops

## Steps to Reproduce (for bugs)

![shot-2020-08-06_12-26-55](https://user-images.githubusercontent.com/16525140/89521697-434d3180-d7e0-11ea-86f1-55da1d6ec9b2.jpg)

## Your Environment

* Version used: commit 9effbcdbdf0b371d4bfec50971798c304751d653
* Environment name and version (e.g. Python 2.7): Python 3.6.9
* Operating System and version (desktop or mobile): Ubuntu 18.04

**Comment by muckelba** [comment]
Do you have pokemon in your Database?

**Comment by xenud** [comment]
No, how can I insert them? But I don't even see pokestops and gyms

**Comment by sn0opy** [comment]
not sure if you seen my message on Discord. RocketMAD is just a frontend. It doesn't scan for anything. You must use https://github.com/map-a-droid/mad which will do the scanning part. You can then use RM to display the data that has been scanned via MAD.
