### ISSUE TITLE
Missing _unknown.png files

### ISSUE THREAD

**Issue by reedy** [cecpk/RocketMAD#176]
Reported on Discord...

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/d/RocketMAD/rocketmad/../static/images/gym/Mystic_6_unknown.png'
```

The `unknown` images are seemingly referenced/used at https://github.com/cecpk/RocketMAD/blob/9c7f2c8084dbef00e04ad6b97204db599c1453bf/rocketmad/dyn_img.py#L488 but don't exist in https://github.com/cecpk/RocketMAD/tree/9c7f2c8084dbef00e04ad6b97204db599c1453bf/static/images/gym

Reporter
>I found the image on the map that isn't displayed
>a mega charizard X raid is going on there :heh:

Presumably if the code uses them.. They should exist in the repo?

**Comment by daangroot** [comment]
I will soon rework the icon generation system, which will fix this issue.
