### ISSUE TITLE
[Bug] Quests are not translated

### ISSUE THREAD

**Issue by lzibeti** [cecpk/RocketMAD#187]
## Expected Behavior

When adding the quests translations to the "pt_br.json" file, RocketMad should display the quests translations instead of displaying them in English.

## Current Behavior

When adding the translations of the quests in the file "pt_br.json" (and pt_br.min.json) Rocktmad does not load the translation, keeping the quest in English.

Example:
![image](https://user-images.githubusercontent.com/58938473/97783003-a4806900-1b73-11eb-9daa-744dd62d2c7c.png)

The translations of the rewards are displayed correctly.

## Possible Solution

Maybe it is being displayed directly from the database, without going through the translation function.
The rest of Rocketmap texts (including quests rewards) are translated correctly.

## Steps to Reproduce (for bugs)

1. Configure RocketMad with the following option: "locale: pt_br"

2. Replace the file "pt_br.json" located in "static/locales/" with the file below
[pt_br.zip](https://github.com/cecpk/RocketMAD/files/5469352/pt_br.zip)

3. Replace the file "pt_br.min.json" located in "static/dist/locales/" with the file below (or run "npm install && npm run build" generating a new file "pt_br.min.json")
[pt_br.min.json.zip](https://github.com/cecpk/RocketMAD/files/5469364/pt_br.min.json.zip)

4. Run RocktMad and check the list of quests in the "Quests" menu

## Context

I'm translating RocketMap to Portuguese Brazil.

## Your Environment

* Version used:  Latest version of Rocketmad (master - Last commit 20e669295146e1cfda6bfe8444569d2883deb9a2 - Support for PokeMiners icons) 

* Environment name and version: 

Python 3.6.9
Npm 6.14.8
Ubuntu Server 18.04.4 LTS
mysql  Ver 15.1 Distrib 10.1.47-MariaDB

* Operating System and version: All browsers (desktop and mobile)

**Comment by na-ji** [comment]
Hello,

(It has already been answered on Discord, but I will add it here too for prosperity.)
It's true that RocketMAD does not handle the quest translation. Right now, MAD is responsible for doing this since it's MAD who is building the task from the proto.
Translating the tasks in RocketMAD with the current system would be much more complex, since a lot of things can vary -> number of things to do, type of raid/throw to do, pokémon to catch etc.
It would be easier to add those translations on MAD's side since they have a more advanced translation system.

**Comment by lzibeti** [comment]
Thanks for the answer. I will check the MAD translation then.

In any case, is it possible to update the file "pt_br.json" in the RocketMap project as soon as I finish?

I believe it is a great help for teams that use RocketMap in Portuguese Brazil

**Comment by na-ji** [comment]
Your update is welcome, do not hesitate to make a PR. 😉
