### ISSUE TITLE
Login button missing on mobile phones in vertical mode

### ISSUE THREAD

**Issue by 0oOSpikeOo0** [cecpk/RocketMAD#208]
## Summary
The login button is missing for users with mobile phones in vertical mode. 

![IMG_20210403_203122](https://user-images.githubusercontent.com/82054515/113759155-0cd00980-9715-11eb-835f-6f90782a10b5.jpg)

The issue started to occur after uncommenting "#no-quests " in the config.

Tested and reproduced with multiple phones (android/ios) / different browsers. 

Stuff like hiding the stats page / making the title shorter via config does not help to make the login button visible. 

As a workaround the user can:
- turn the device horizontally and click the login button 
![IMG_20210403_203154](https://user-images.githubusercontent.com/82054515/113759734-b7e0c300-9715-11eb-8b9c-19f2b75f53dd.jpg)
- navigate directly to https://[some_url]/login

## Expected Behavior
The login button is shown for users with mobile phones in vertical mode. 

## Current Behavior
The login button is missing for users with mobile phones in vertical mode. 

## Possible Solution
-

## Steps to Reproduce (for bugs)
1. uncomment "#no-quests " in the config and restart RocketMad
2. take a phone, hold it vertically 
3. browse to your RocketMad
4. log out if needed

## Context
Users cannot login in this pretty default usecase

## Your Environment

* Version used: current master
* Environment name and version (e.g. Python 2.7): Python 3.6.9
* Operating System and version (desktop or mobile): mobile - ios/android / firefox/chrome/safari

**Comment by daangroot** [comment]
Fixed.
